export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_USER = "CLEAR_USER";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const SET_POEM = "SET_POEM";
export const CLEAR_POEM = "CLEAR_POEM";

export const SET_POEMS = "SET_POEMS";
export const CLEAR_POEMS = "CLEAR_POEMS";

export const SET_PROFILE = "SET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const SET_USERS = "SET_USERS";
export const CLEAR_USERS = "CLEAR_USERS";

export const CURRENT_USER_INFO = "CURRENT_USER_INFO";
export const CLEAR_CURRENT_USER_INFO = "CLEAR_CURRENT_USER_INFO";

export const POEM_NOTIFICATION = "POEM_NOTIFICATION";
export const MESSAGE_NOTIFICATION = "MESSAGE_NOTIFICATION";

export const GET_MESSAGES = "GET_MESSAGES";

export const SHOW_POEM_MODAL = "SHOW_POEM_MODAL";
export const HIDE_POEM_MODAL = "SHOW_POEM_MODAL";

export const GET_LOGGED_IN_GROUPS = "GET_LOGGED_IN_GROUPS";
export const GET_SINGLE_GROUP = "GET_SINGLE_GROUP";

export const GET_SEARCH = "GET_SEARCH";

export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";
